# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-mysql
version:      1.00
version_from: lib/Class/DBI/mysql.pm
installdirs:  site
requires:
    Class::DBI:                    0.94
    DBD::mysql:                    0
    Test::More:                    0.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
